[package]
name = "mercury"
version = "0.1.0"
authors = ["thojest <thojest@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "libmercury"
path = "src/lib.rs"

[[bin]]
name = "mercury"
path = "src/bin.rs"


[dependencies]
snap = "1"
byteorder = "1"