[package]
name = "blockbender"
version = "0.1.0"
authors = ["thojest <thojest@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "libblockbender"
path = "src/lib.rs"

[[bin]]
name = "blockbender"
path = "src/bin.rs"


[dependencies]
ethane = "0.1.0"
druid = { git = "https://github.com/linebender/druid"}
dotenv = "0.15"
