[package]
name = "mercury"
version = "0.1.0"
authors = ["thojest <thojest@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
thiserror = "1"
byteorder = "1"
snap = "1"

[dev-dependencies]
dotenv = "0.15"
criterion = "0.3"

[lib]
bench = false

[[bench]]
name = "freezer_load"
harness = false
